server.name: wine-kibana
server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

# Configuración de visualizaciones por defecto
xpack.reporting.enabled: true
xpack.spaces.enabled: true
